### ISSUE TITLE
Resets conts over 1000

### ISSUE THREAD

**Issue by ilinet-zagreb** [justintadlock/entry-views#2] opened 2015-03-12 15:25 UTC
Hi. Great plugin. We are using it with the Voice theme and it is not going over 1000, then it rolls back at 100…can you tell us whats wrong?

The site is: http://www.djecjaposla.com/

**Comment by justintadlock** [comment] 2015-03-12 20:46
I cannot reproduce this issue with a basic WP install and one of the default WordPress themes active.  I'm closing this ticket as invalid.

If you're having issues, I recommend posting on the plugin's [support forum](http://themehybrid.com/board/topics) so that we can take a look at what's going on specifically with your site.

**Closed as completed by justintadlock** 2015-03-12 20:46 UTC
Labels: invalid
